## exp 1
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import torch
import numpy as np

torch.__version__

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

x = torch.from_numpy(arr)
print(x)

print(x.dtype)

print(type(x))
print(x.type())

arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

arr[2]=77
print(t)

arr = np.arange(0,5)
t = torch.tensor(arr)
print(t)

arr[2]=77
print(t)

data = np.array([1,2,3])

a = torch.Tensor(data)
print(a, a.type())

b = torch.tensor(data)
print(b, b.type())

c = torch.tensor(data, dtype=torch.long)
print(c, c.type())

x = torch.empty(4, 3)
print(x)

x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

x = torch.arange(0,18,2).reshape(3,3)
print(x)

x = torch.linspace(0,18,12).reshape(3,4)
print(x)

x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

print('Old:', x.type())
x = x.type(torch.int64)
print('New:', x.type())

x = torch.rand(4, 3)
print(x)

x = torch.randn(4, 3)
print(x)

x = torch.randint(0, 5, (4, 3))
print(x)

x = torch.zeros(2,5)
print(x)

x2 = torch.randn_like(x)
print(x2)

x3 = torch.ones_like(x2)
print(x3)

torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

x.shape

x.size()

x.device

x.layout

## exp 2
import torch
import numpy as np

x = torch.arange(6).reshape(3,2)
print(x)

x[:,1]

x[:,1:]

x = torch.arange(10)
print(x)

x.view(2,5)

x.view(5,2)

x

z = x.view(2,5)
x[0]=234
print(z)

x.view(2,-1)

x.view(-1,5)

x.view_as(z)

a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

print(torch.add(a, b))

result = torch.empty(3)
torch.add(a, b, out=result)
print(result)

a.add_(b)
print(a)

a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(torch.add(a,b).sum())

a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a.mul(b))
print()
print(a.dot(b))

a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print(torch.mm(a,b))

print(a.mm(b))

print(a @ b)

t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)
print(torch.matmul(t1, t2).size())

print(torch.mm(t1, t2).size())

x = torch.tensor([2.,5.,8.,14.])
x.norm()

x = torch.ones(3,7)
x.numel()
